name: Initiate Challenges...

on:
  schedule:
    - cron: '2 * * * *'

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Action to create issues stating ideas for new projects!
        uses: ArnavK-09/create-this-project@v0.0.1-testing
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
