name: Initiate Challenges...

on:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - name: Action to create issues stating ideas for new projects!
        uses: ArnavK-09/create-this-project@action
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
